title: 给忙碌者的育儿攻略
author:
  name: pythias
  email: pythias@gmail.com
description: >- 
  个人观点，仅供参考。如有雷同，纯属巧合。
baseurl: ""
url: "https://pythias.github.io"
timezone: Asia/Shanghai
updated_at: 2020-03-10 16:45
google_analytics: G-VKB8V54Q4T
baidu_analytics: 8aad084bec1278763ad2c403badf54e5

minima:
  social_links:
    github: pythias
    weibo: 1763952531
    weibo_username: 陈杰要骑车

header_pages:
 - 
  url: /topic.html
  title: 话题
 - 
  url: /sport.html
  title: 体育
 - 
  url: /education.html
  title: 教育
 - 
  url: /gallery
  title: 作品
 - 
  url: /about.html
  title: 关于

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  topics:
    output: true
    permalink: /topic/:name.html
  shoppings:
    output: true
    permalink: /shopping/:name.html
  educations:
    output: true
    permalink: /education/:name.html
  sports:
    output: true
    permalink: /sport/:name.html
  references:
    output: true
    permalink: /reference/:name.html
  works:
    output: true
    permalink: /works/:year/:month/:day/:name.html

sass:
  sass_dir: _sass

gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  title: ':title - 第:num/:max页'

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - README.md